// Define roles for the application
export const ROLES = {
    STUDENT: "student",
    TEACHER: "teacher",
    UNIADMIN: "uniadmin",
    ADMIN: "admin"
}

// Define permissions for each role
export const PERMISSIONS = {

    CREATE_POST : [ROLES.TEACHER, ROLES.UNIADMIN],
    DELETE_POST : [ROLES.UNIADMIN, ROLES.TEACHER],

    //Course related permissions
    CREATE_QNA : [ROLES.TEACHER],
    CREATE_ASSIGNMENT : [ROLES.TEACHER],
    EDIT_ASSIGMENT : [ROLES.TEACHER],
    DELETE_ASSIGNMENT : [ROLES.TEACHER],
    CREATE_COURSE : [ROLES.TEACHER],
    DELETE_COURSE : [ROLES.TEACHER],
    EDIT_COURSE : [ROLES.TEACHER],
    CREATE_TOPIC : [ROLES.TEACHER],
    DELETE_TOPIC : [ROLES.TEACHER],
    CREATE_SUBTOPIC: [ROLES.TEACHER],
    DELETE_SUBTOPIC: [ROLES.TEACHER],
    EDIT_SUBTOPIC: [ROLES.TEACHER],

    ENROLL_STUDENT : [ROLES.TEACHER],
    UNENROLL_STUDENT : [ROLES.TEACHER],

    CREATE_QUIZ : [ROLES.TEACHER],
    DELETE_QUIZ : [ROLES.TEACHER],
    EDIT_QUIZ : [ROLES.TEACHER],

    DELETE_GLOBAL_EVENT: [ROLES.TEACHER]
}